# models/nutrition.py
#
# Calorie and standard portion data for all 101 Food-101 classes.
# calories_per_100g: kcal per 100g (used for calorie calculation)
# standard_portion_g: typical single serving in grams (used by depth estimator)
#
# Sources: USDA FoodData Central averages + standard nutritional references.
# Values are approximate — exact calories depend on recipe and preparation.

FOOD_DATA: dict[str, dict] = {
    "apple_pie":              {"cal": 237, "portion": 125},
    "baby_back_ribs":         {"cal": 295, "portion": 300},
    "baklava":                {"cal": 428, "portion": 80},
    "beef_carpaccio":         {"cal": 160, "portion": 100},
    "beef_tartare":           {"cal": 195, "portion": 150},
    "beet_salad":             {"cal": 70,  "portion": 150},
    "beignets":               {"cal": 380, "portion": 100},
    "bibimbap":               {"cal": 130, "portion": 400},
    "bread_pudding":          {"cal": 250, "portion": 150},
    "breakfast_burrito":      {"cal": 215, "portion": 250},
    "bruschetta":             {"cal": 195, "portion": 100},
    "caesar_salad":           {"cal": 110, "portion": 200},
    "cannoli":                {"cal": 370, "portion": 85},
    "caprese_salad":          {"cal": 145, "portion": 180},
    "carrot_cake":            {"cal": 415, "portion": 100},
    "ceviche":                {"cal": 75,  "portion": 150},
    "cheesecake":             {"cal": 320, "portion": 120},
    "cheese_plate":           {"cal": 380, "portion": 80},
    "chicken_curry":          {"cal": 150, "portion": 350},
    "chicken_quesadilla":     {"cal": 220, "portion": 200},
    "chicken_wings":          {"cal": 290, "portion": 250},
    "chocolate_cake":         {"cal": 370, "portion": 100},
    "chocolate_mousse":       {"cal": 230, "portion": 120},
    "churros":                {"cal": 375, "portion": 100},
    "clam_chowder":           {"cal": 80,  "portion": 350},
    "club_sandwich":          {"cal": 230, "portion": 250},
    "crab_cakes":             {"cal": 175, "portion": 150},
    "creme_brulee":           {"cal": 240, "portion": 120},
    "croque_madame":          {"cal": 260, "portion": 200},
    "cup_cakes":              {"cal": 375, "portion": 60},
    "deviled_eggs":           {"cal": 190, "portion": 100},
    "donuts":                 {"cal": 450, "portion": 60},
    "dumplings":              {"cal": 155, "portion": 200},
    "edamame":                {"cal": 120, "portion": 150},
    "eggs_benedict":          {"cal": 270, "portion": 220},
    "escargots":              {"cal": 115, "portion": 100},
    "falafel":                {"cal": 330, "portion": 150},
    "filet_mignon":           {"cal": 250, "portion": 200},
    "fish_and_chips":         {"cal": 270, "portion": 400},
    "foie_gras":              {"cal": 460, "portion": 80},
    "french_fries":           {"cal": 312, "portion": 150},
    "french_onion_soup":      {"cal": 65,  "portion": 350},
    "french_toast":           {"cal": 228, "portion": 150},
    "fried_calamari":         {"cal": 225, "portion": 150},
    "fried_rice":             {"cal": 163, "portion": 300},
    "frozen_yogurt":          {"cal": 159, "portion": 150},
    "garlic_bread":           {"cal": 350, "portion": 80},
    "gnocchi":                {"cal": 130, "portion": 250},
    "greek_salad":            {"cal": 95,  "portion": 200},
    "grilled_cheese_sandwich":{"cal": 350, "portion": 150},
    "grilled_salmon":         {"cal": 208, "portion": 180},
    "guacamole":              {"cal": 160, "portion": 100},
    "gyoza":                  {"cal": 200, "portion": 150},
    "hamburger":              {"cal": 295, "portion": 250},
    "hot_and_sour_soup":      {"cal": 55,  "portion": 350},
    "hot_dog":                {"cal": 310, "portion": 100},
    "huevos_rancheros":       {"cal": 190, "portion": 250},
    "hummus":                 {"cal": 170, "portion": 100},
    "ice_cream":              {"cal": 207, "portion": 130},
    "lasagna":                {"cal": 135, "portion": 350},
    "lobster_bisque":         {"cal": 100, "portion": 350},
    "lobster_roll_sandwich":  {"cal": 230, "portion": 200},
    "macaroni_and_cheese":    {"cal": 170, "portion": 300},
    "macarons":               {"cal": 410, "portion": 50},
    "miso_soup":              {"cal": 40,  "portion": 300},
    "mussels":                {"cal": 86,  "portion": 200},
    "nachos":                 {"cal": 305, "portion": 200},
    "omelette":               {"cal": 155, "portion": 200},
    "onion_rings":            {"cal": 410, "portion": 150},
    "oysters":                {"cal": 69,  "portion": 150},
    "pad_thai":               {"cal": 160, "portion": 350},
    "paella":                 {"cal": 190, "portion": 350},
    "pancakes":               {"cal": 225, "portion": 200},
    "panna_cotta":            {"cal": 220, "portion": 130},
    "peking_duck":            {"cal": 340, "portion": 200},
    "pho":                    {"cal": 60,  "portion": 500},
    "pizza":                  {"cal": 266, "portion": 200},
    "pork_chop":              {"cal": 250, "portion": 200},
    "poutine":                {"cal": 260, "portion": 300},
    "prime_rib":              {"cal": 300, "portion": 250},
    "pulled_pork_sandwich":   {"cal": 240, "portion": 250},
    "ramen":                  {"cal": 110, "portion": 500},
    "ravioli":                {"cal": 180, "portion": 250},
    "red_velvet_cake":        {"cal": 395, "portion": 100},
    "risotto":                {"cal": 145, "portion": 300},
    "samosa":                 {"cal": 260, "portion": 100},
    "sashimi":                {"cal": 130, "portion": 150},
    "scallops":               {"cal": 111, "portion": 150},
    "seaweed_salad":          {"cal": 70,  "portion": 100},
    "shrimp_and_grits":       {"cal": 175, "portion": 300},
    "spaghetti_bolognese":    {"cal": 130, "portion": 350},
    "spaghetti_carbonara":    {"cal": 185, "portion": 350},
    "spring_rolls":           {"cal": 200, "portion": 150},
    "steak":                  {"cal": 250, "portion": 220},
    "strawberry_shortcake":   {"cal": 310, "portion": 120},
    "sushi":                  {"cal": 145, "portion": 200},
    "tacos":                  {"cal": 220, "portion": 200},
    "takoyaki":               {"cal": 200, "portion": 150},
    "tiramisu":               {"cal": 285, "portion": 120},
    "tuna_tartare":           {"cal": 130, "portion": 150},
    "waffles":                {"cal": 290, "portion": 200},
}

DEFAULT_CAL     = 200   # fallback kcal/100g
DEFAULT_PORTION = 200   # fallback portion in grams

# ── Extended: Eastern European, everyday & home-cooked foods ─────────────────
FOOD_DATA.update({
    # ── Soups & stews ─────────────────────────────────────────────────────────
    "borscht":                    {"cal": 45,  "portion": 400},
    "solyanka":                   {"cal": 65,  "portion": 350},
    "rassolnik":                  {"cal": 55,  "portion": 350},
    "shchi":                      {"cal": 40,  "portion": 400},  # cabbage soup
    "okroshka":                   {"cal": 50,  "portion": 350},
    "chicken_soup":               {"cal": 45,  "portion": 400},
    "pea_soup":                   {"cal": 85,  "portion": 350},
    "mushroom_soup":              {"cal": 50,  "portion": 350},
    "lentil_soup":                {"cal": 90,  "portion": 350},
    "tomato_soup":                {"cal": 60,  "portion": 350},
    "vegetable_soup":             {"cal": 40,  "portion": 350},
    "fish_soup":                  {"cal": 55,  "portion": 350},
    "beef_stew":                  {"cal": 120, "portion": 400},
    "pork_stew":                  {"cal": 130, "portion": 400},
    "goulash":                    {"cal": 140, "portion": 350},
    "hodgepodge":                 {"cal": 65,  "portion": 350},

    # ── Plov & rice dishes ────────────────────────────────────────────────────
    "plov":                       {"cal": 185, "portion": 350},
    "pilaf":                      {"cal": 185, "portion": 350},
    "rice_with_meat":             {"cal": 165, "portion": 350},
    "rice_with_vegetables":       {"cal": 120, "portion": 300},
    "buckwheat":                  {"cal": 110, "portion": 250},
    "buckwheat_with_meat":        {"cal": 150, "portion": 300},
    "porridge":                   {"cal": 85,  "portion": 250},
    "oatmeal":                    {"cal": 70,  "portion": 250},
    "semolina":                   {"cal": 80,  "portion": 250},

    # ── Potato dishes ─────────────────────────────────────────────────────────
    "mashed_potato":              {"cal": 110, "portion": 300},
    "boiled_potato":              {"cal": 85,  "portion": 250},
    "fried_potato":               {"cal": 190, "portion": 200},
    "potato_salad":               {"cal": 140, "portion": 200},
    "potato_pancakes":            {"cal": 215, "portion": 150},
    "potato_casserole":           {"cal": 130, "portion": 300},

    # ── Meat dishes ───────────────────────────────────────────────────────────
    "schnitzel":                  {"cal": 280, "portion": 200},
    "pork_schnitzel":             {"cal": 280, "portion": 200},
    "chicken_schnitzel":          {"cal": 230, "portion": 180},
    "meatballs":                  {"cal": 195, "portion": 200},
    "meatball_soup":              {"cal": 70,  "portion": 350},
    "kotlet":                     {"cal": 250, "portion": 150},  # fried meat patty
    "roast_pork":                 {"cal": 270, "portion": 200},
    "roast_chicken":              {"cal": 215, "portion": 250},
    "grilled_chicken":            {"cal": 195, "portion": 200},
    "fried_chicken":              {"cal": 265, "portion": 200},
    "chicken_breast":             {"cal": 165, "portion": 180},
    "sausage":                    {"cal": 310, "portion": 100},
    "smoked_sausage":             {"cal": 340, "portion": 100},
    "hot_dog_sausage":            {"cal": 300, "portion": 80},
    "liver":                      {"cal": 135, "portion": 150},
    "liver_with_onions":          {"cal": 155, "portion": 180},

    # ── Pasta & dumplings ─────────────────────────────────────────────────────
    "pasta":                      {"cal": 130, "portion": 300},
    "pasta_with_meat":            {"cal": 165, "portion": 350},
    "macaroni":                   {"cal": 130, "portion": 300},
    "pelmeni":                    {"cal": 210, "portion": 250},   # meat dumplings
    "varenyky":                   {"cal": 175, "portion": 250},   # Ukrainian dumplings
    "pierogi":                    {"cal": 180, "portion": 250},
    "manty":                      {"cal": 195, "portion": 250},   # Central Asian dumplings

    # ── Salads ────────────────────────────────────────────────────────────────
    "olivier_salad":              {"cal": 195, "portion": 200},   # Russian salad
    "vinegret":                   {"cal": 80,  "portion": 200},   # beet & vegetable salad
    "cabbage_salad":              {"cal": 45,  "portion": 150},
    "cucumber_tomato_salad":      {"cal": 30,  "portion": 150},
    "carrot_salad":               {"cal": 55,  "portion": 150},

    # ── Bread & bakery ────────────────────────────────────────────────────────
    "black_bread":                {"cal": 210, "portion": 60},
    "rye_bread":                  {"cal": 215, "portion": 60},
    "white_bread":                {"cal": 265, "portion": 60},
    "dark_bread":                 {"cal": 210, "portion": 60},
    "bun":                        {"cal": 290, "portion": 80},
    "toast":                      {"cal": 265, "portion": 30},

    # ── Dairy & eggs ──────────────────────────────────────────────────────────
    "cottage_cheese":             {"cal": 98,  "portion": 150},
    "sour_cream":                 {"cal": 210, "portion": 30},
    "kefir":                      {"cal": 55,  "portion": 250},
    "ryazhenka":                  {"cal": 65,  "portion": 250},
    "milk":                       {"cal": 60,  "portion": 250},
    "fried_egg":                  {"cal": 185, "portion": 100},
    "boiled_egg":                 {"cal": 155, "portion": 100},
    "scrambled_eggs":             {"cal": 170, "portion": 150},

    # ── Fruits ────────────────────────────────────────────────────────────────
    "banana":                     {"cal": 89,  "portion": 120},
    "apple":                      {"cal": 52,  "portion": 180},
    "orange":                     {"cal": 47,  "portion": 150},
    "pear":                       {"cal": 57,  "portion": 170},
    "grape":                      {"cal": 69,  "portion": 150},
    "watermelon":                 {"cal": 30,  "portion": 300},
    "strawberry":                 {"cal": 33,  "portion": 150},
    "tangerine":                  {"cal": 53,  "portion": 100},
    "pomegranate":                {"cal": 83,  "portion": 150},
    "peach":                      {"cal": 39,  "portion": 150},
    "plum":                       {"cal": 46,  "portion": 100},
    "cherry":                     {"cal": 63,  "portion": 100},
    "blueberry":                  {"cal": 57,  "portion": 100},

    # ── Vegetables (common sides) ─────────────────────────────────────────────
    "cabbage":                    {"cal": 25,  "portion": 150},
    "stewed_cabbage":             {"cal": 55,  "portion": 200},
    "carrot":                     {"cal": 41,  "portion": 100},
    "beetroot":                   {"cal": 43,  "portion": 100},
    "cucumber":                   {"cal": 15,  "portion": 100},
    "tomato":                     {"cal": 18,  "portion": 100},
    "onion":                      {"cal": 40,  "portion": 80},
    "mushrooms":                  {"cal": 22,  "portion": 100},
    "fried_mushrooms":            {"cal": 95,  "portion": 150},

    # ── Drinks (low cal — included so corrections work) ───────────────────────
    "tea":                        {"cal": 2,   "portion": 250},
    "coffee":                     {"cal": 5,   "portion": 200},
    "juice":                      {"cal": 45,  "portion": 250},
    "compote":                    {"cal": 40,  "portion": 250},
    "kvas":                       {"cal": 27,  "portion": 250},

    # ── Sandwiches ────────────────────────────────────────────────────────────
    "sandwich":                   {"cal": 230, "portion": 150},
    "open_sandwich":              {"cal": 180, "portion": 120},
    "cheese_sandwich":            {"cal": 280, "portion": 150},
    "ham_sandwich":               {"cal": 250, "portion": 150},
    "butter_bread":               {"cal": 280, "portion": 80},
})


def get_calories_per_100g(label: str) -> int:
    # Model labels use underscores; normalise just in case
    key = label.lower().replace(" ", "_").replace("-", "_")
    return FOOD_DATA.get(key, {}).get("cal", DEFAULT_CAL)


def get_standard_portion(label: str) -> int:
    key = label.lower().replace(" ", "_").replace("-", "_")
    return FOOD_DATA.get(key, {}).get("portion", DEFAULT_PORTION)


# ── Estonian aliases → English nutrition keys ─────────────────────────────────
# Keys: lowercase Estonian food names (+ common spelling variants)
# Values: must match a key in FOOD_DATA above

ET_ALIASES: dict[str, str] = {
    'borš': 'borscht',
    'borsš': 'borscht',
    'borshch': 'borscht',
    'segansupp': 'solyanka',
    'hapukurgisupp': 'rassolnik',
    'kapsasupp': 'shchi',
    'kanasupp': 'chicken_soup',
    'hernesupp': 'pea_soup',
    'seenesupp': 'mushroom_soup',
    'läätsesuppp': 'lentil_soup',
    'tomatisupp': 'tomato_soup',
    'köögiviljasupp': 'vegetable_soup',
    'kalasupp': 'fish_soup',
    'lihahautis': 'beef_stew',
    'veiselihahautis': 'beef_stew',
    'seahautis': 'pork_stew',
    'guljašš': 'goulash',
    'guljash': 'goulash',
    'plovi': 'plov',
    'riis lihaga': 'rice_with_meat',
    'riis köögiviljaga': 'rice_with_vegetables',
    'tatar': 'buckwheat',
    'tatrapuder': 'buckwheat',
    'tatar lihaga': 'buckwheat_with_meat',
    'puder': 'porridge',
    'kaerapuder': 'oatmeal',
    'kaerahelbed': 'oatmeal',
    'mannapuder': 'semolina',
    'kartulipuder': 'mashed_potato',
    'püree': 'mashed_potato',
    'kartulipüree': 'mashed_potato',
    'keedetud kartul': 'boiled_potato',
    'keedetud kartulid': 'boiled_potato',
    'kartul': 'boiled_potato',
    'kartulid': 'boiled_potato',
    'praekartul': 'fried_potato',
    'praetud kartul': 'fried_potato',
    'kartulisalat': 'potato_salad',
    'kartulipannkoogid': 'potato_pancakes',
    'kartuliplaadid': 'potato_pancakes',
    'kartulivorm': 'potato_casserole',
    'šnitsel': 'schnitzel',
    'seašnitsel': 'pork_schnitzel',
    'kanašnitsel': 'chicken_schnitzel',
    'lihapallid': 'meatballs',
    'lihapall': 'meatballs',
    'lihapallide supp': 'meatball_soup',
    'kotlet': 'kotlet',
    'praesea': 'roast_pork',
    'praekana': 'roast_chicken',
    'grillkana': 'grilled_chicken',
    'praetud kana': 'fried_chicken',
    'kanafilee': 'chicken_breast',
    'vorst': 'sausage',
    'vorstid': 'sausage',
    'suitsuvorst': 'smoked_sausage',
    'maks': 'liver',
    'maks sibulaga': 'liver_with_onions',
    'sealiha': 'pork_chop',
    'veiseliha': 'steak',
    'praeliha': 'steak',
    'makaronid': 'pasta',
    'pasta': 'pasta',
    'makaronid lihaga': 'pasta_with_meat',
    'pelmeenid': 'pelmeni',
    'varenikud': 'varenyky',
    'mantid': 'manty',
    'olivjesalat': 'olivier_salad',
    'olivje': 'olivier_salad',
    'vinegrett': 'vinegret',
    'kapsasalat': 'cabbage_salad',
    'kurgi-tomatisalat': 'cucumber_tomato_salad',
    'porgandisalat': 'carrot_salad',
    'must leib': 'black_bread',
    'rukkileib': 'rye_bread',
    'valge leib': 'white_bread',
    'leib': 'black_bread',
    'sai': 'white_bread',
    'kukkel': 'bun',
    'röstsai': 'toast',
    'kodujuust': 'cottage_cheese',
    'hapukoor': 'sour_cream',
    'keefir': 'kefir',
    'rjaženka': 'ryazhenka',
    'piim': 'milk',
    'praetud muna': 'fried_egg',
    'praemuna': 'fried_egg',
    'keedetud muna': 'boiled_egg',
    'keedumuna': 'boiled_egg',
    'munapuder': 'scrambled_eggs',
    'omlett': 'omelette',
    'omlet': 'omelette',
    'banaan': 'banana',
    'banaanid': 'banana',
    'õun': 'apple',
    'õunad': 'apple',
    'apelsin': 'orange',
    'apelsinid': 'orange',
    'pirn': 'pear',
    'pirnid': 'pear',
    'viinamarjad': 'grape',
    'viinamarjas': 'grape',
    'arbuus': 'watermelon',
    'maasikas': 'strawberry',
    'maasikad': 'strawberry',
    'mandariin': 'tangerine',
    'mandariinid': 'tangerine',
    'granaatõun': 'pomegranate',
    'virsik': 'peach',
    'virsikud': 'peach',
    'ploom': 'plum',
    'ploomid': 'plum',
    'kirss': 'cherry',
    'kirsid': 'cherry',
    'mustikas': 'blueberry',
    'mustikad': 'blueberry',
    'kapsas': 'cabbage',
    'hautatud kapsas': 'stewed_cabbage',
    'porgand': 'carrot',
    'porgandid': 'carrot',
    'peet': 'beetroot',
    'peedid': 'beetroot',
    'kurk': 'cucumber',
    'kurgid': 'cucumber',
    'tomat': 'tomato',
    'tomatid': 'tomato',
    'sibul': 'onion',
    'sibulad': 'onion',
    'seen': 'mushrooms',
    'seened': 'mushrooms',
    'praetud seened': 'fried_mushrooms',
    'tee': 'tea',
    'kohv': 'coffee',
    'mahl': 'juice',
    'kompott': 'compote',
    'kali': 'kvas',
    'pitsa': 'pizza',
    'hamburger': 'hamburger',
    'friikartulid': 'french_fries',
    'vahvlid': 'waffles',
    'pannkoogid': 'pancakes',
    'jäätis': 'ice_cream',
    'juustukook': 'cheesecake',
    'šokolaadikook': 'chocolate_cake',
    'kanakarri': 'chicken_curry',
    'sushi': 'sushi',
    'nuudlid': 'ramen',
    'krevettid': 'shrimp_and_grits',
    'lõhe': 'grilled_salmon',
    'tuunikala': 'tuna_tartare',
    'kalmaar': 'fried_calamari',
    'rannakarbid': 'mussels',
    'austrid': 'oysters',
    'õunakook': 'apple_pie',
    'ribi': 'baby_back_ribs',
    'baklava': 'baklava',
    'veiseliha carpaccio': 'beef_carpaccio',
    'veiseliha tataar': 'beef_tartare',
    'peedisalat': 'beet_salad',
    'sõõrikud': 'donuts',
    'bibimbap': 'bibimbap',
    'leivapuding': 'bread_pudding',
    'hommikusöögiburritos': 'breakfast_burrito',
    'bruschetta': 'bruschetta',
    'caesar salat': 'caesar_salad',
    'cannoli': 'cannoli',
    'caprese salat': 'caprese_salad',
    'porgandikook': 'carrot_cake',
    'ceviche': 'ceviche',
    'juustukook': 'cheesecake',
    'juustutaldrik': 'cheese_plate',
    'kanakarri': 'chicken_curry',
    'kana quesadilla': 'chicken_quesadilla',
    'kanakoivad': 'chicken_wings',
    'šokolaadikook': 'chocolate_cake',
    'šokolaadivaht': 'chocolate_mousse',
    'churros': 'churros',
    'karpsupp': 'clam_chowder',
    'klubi võileib': 'club_sandwich',
    'krabikoogid': 'crab_cakes',
    'creme brulee': 'creme_brulee',
    'croque madame': 'croque_madame',
    'koogikesed': 'cup_cakes',
    'täidetud munad': 'deviled_eggs',
    'pelmeenid': 'dumplings',
    'edamame': 'edamame',
    'eggs benedict': 'eggs_benedict',
    'teod': 'escargots',
    'falafel': 'falafel',
    'filee mignon': 'filet_mignon',
    'kala ja friikartulid': 'fish_and_chips',
    'foie gras': 'foie_gras',
    'prantsuse röstsai': 'french_toast',
    'kalmaarid': 'fried_calamari',
    'praetud riis': 'fried_rice',
    'külmutatud jogurt': 'frozen_yogurt',
    'küüslauguleib': 'garlic_bread',
    'gnocchi': 'gnocchi',
    'kreeka salat': 'greek_salad',
    'grillitud juustuvõileib': 'grilled_cheese_sandwich',
    'guacamole': 'guacamole',
    'gyoza': 'gyoza',
    'vürtsikas hapusupp': 'hot_and_sour_soup',
    'hot dog': 'hot_dog',
    'huevos rancheros': 'huevos_rancheros',
    'hummus': 'hummus',
    'lasanje': 'lasagna',
    'homarisupp': 'lobster_bisque',
    'homari võileib': 'lobster_roll_sandwich',
    'makaronid juustuga': 'macaroni_and_cheese',
    'macarons': 'macarons',
    'misosuppp': 'miso_soup',
    'misosupp': 'miso_soup',
    'rannakarbid': 'mussels',
    'nachos': 'nachos',
    'sibularõngad': 'onion_rings',
    'austrid': 'oysters',
    'pad thai': 'pad_thai',
    'paella': 'paella',
    'panna cotta': 'panna_cotta',
    'pekingi part': 'peking_duck',
    'pho': 'pho',
    'seakotlet': 'pork_chop',
    'poutine': 'poutine',
    'prime rib': 'prime_rib',
    'tõmmatud sealiha võileib': 'pulled_pork_sandwich',
    'ramen': 'ramen',
    'ravioolid': 'ravioli',
    'punane sametkook': 'red_velvet_cake',
    'risoto': 'risotto',
    'samosa': 'samosa',
    'sashimi': 'sashimi',
    'kammkarbid': 'scallops',
    'merevetikasalat': 'seaweed_salad',
    'krevetid': 'shrimp_and_grits',
    'spagetid bolognese': 'spaghetti_bolognese',
    'spagetid carbonara': 'spaghetti_carbonara',
    'kevadrullid': 'spring_rolls',
    'praad': 'steak',
    'maasikakook': 'strawberry_shortcake',
    'takod': 'tacos',
    'takoyaki': 'takoyaki',
    'tiramisu': 'tiramisu',
    'tuunikala tataar': 'tuna_tartare',
    'sõõrikud': 'beignets',
    'prantsuse sibulsupp': 'french_onion_soup',
    'okroshka': 'okroshka',
    'aedviljasupp': 'hodgepodge',
    'pilaf': 'pilaf',
    'hot dog vorst': 'hot_dog_sausage',
    'makaronid': 'macaroni',
    'pelmeenid': 'pelmeni',
    'pierogi': 'pierogi',
    'tume leib': 'dark_bread',
    'sõõrikud': 'donuts',
    'pelmeenid': 'dumplings',
    'berliini sõõrikud': 'beignets',
    'siberi pelmeenid': 'pelmeni',
    'võileib': 'sandwich',
    'võileivad': 'sandwich',
    'lahtine võileib': 'open_sandwich',
    'juustuvõileib': 'cheese_sandwich',
    'singavõileib': 'ham_sandwich',
    'võiga leib': 'butter_bread',
    'leib võiga': 'butter_bread',
    'club võileib': 'club_sandwich',
    'grill juustuvõileib': 'grilled_cheese_sandwich',
}